/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ACAdapter */

#ifndef _Included_ACAdapter
#define _Included_ACAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ACAdapter
 * Method:    isPluggedInWin
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ACAdapter_isPluggedInWin
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
